import type { IFolder } from "@/models/folder.model";
import type { IJob } from "@/models/job.model";
import type { ITask, ITaskStage } from "@/models/task.model";
import type { ISupplier } from "@/models/supplier.model";
import { ETaskProgress, ETaskStatus } from "@/models/task.model";

export const suppliers: ISupplier[] = [
  { id: 1, name: "Wall Frame Co." },
  { id: 2, name: "Truss Pro Inc." },
  { id: 3, name: "Window Experts" },
  { id: 4, name: "Mixer Masters" },
  { id: 5, name: "Brick Supply Ltd." },
  { id: 6, name: "Door Hardware Pro" },
  { id: 7, name: "Site Solutions" },
  { id: 8, name: "Fencing Plus" },
  { id: 9, name: "Water Works Inc." },
  { id: 10, name: "Sign Makers" },
  { id: 11, name: "Toilet Suppliers" },
  { id: 12, name: "Cut Pro Services" },
  { id: 13, name: "Set Out Services" },
  { id: 14, name: "Bored Piers Co." },
  { id: 15, name: "Underground Power" },
  { id: 16, name: "Sewer Storm Drains" },
  { id: 17, name: "Spoil Removal Ltd." },
  { id: 18, name: "Termite Protection" },
  { id: 19, name: "Retaining Walls Co." },
  { id: 20, name: "Steel Inspection" },
  { id: 21, name: "Slab Services" },
  { id: 22, name: "Backfill Pro" },
  { id: 23, name: "Basin Install" },
];

export const taskStages: ITaskStage[] = [
  { id: 1, name: "Base Stage", order: 1 },
  { id: 2, name: "Frame Stage", order: 2 },
];

const baseStageTasks: ITask[] = [
  {
    id: 1,
    jobId: 1,
    name: "Wall Frame Pre Call Up",
    supplierId: 1,
    costCenterId: "CC001",
    progress: ETaskProgress.None,
    status: ETaskStatus.None,
    stageId: 1,
    notes: "this is a really long note to test the notes modal",
    startDate: new Date("2024-01-15"),
    purchaseOrderLinks: [],
    planLinks: ['https://www.google.com'],
    order: 1,
  },
  {
    id: 2,
    jobId: 1,
    name: "Truss Pre Call up",
    supplierId: 2,
    costCenterId: "CC002",
    progress: ETaskProgress.None,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "",
    startDate: new Date("2024-01-16"),
    purchaseOrderLinks: ['https://www.google.com','https://www.youtube.com'],
    planLinks: ['https://www.google.com'],
    order: 2,
  },
  {
    id: 3,
    jobId: 1,
    name: "Window Pre Call Up",
    supplierId: 3,
    costCenterId: "CC003",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "",
    startDate: new Date("2024-01-17"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 3,
  },
  {
    id: 4,
    jobId: 1,
    name: "Wall Mixer Call Up",
    supplierId: 4,
    costCenterId: "CC004",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "",
    startDate: new Date("2024-01-18"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 4,
  },
  {
    id: 5,
    jobId: 1,
    name: "Early Brick Call Up",
    supplierId: 5,
    costCenterId: "CC005",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "if required",
    startDate: new Date("2024-01-19"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 5,
  },
  {
    id: 6,
    jobId: 1,
    name: "External Door Hardware",
    supplierId: 6,
    costCenterId: "CC006",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-01-20"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 6,
  },
  {
    id: 7,
    jobId: 1,
    name: "Site Capo/Bin",
    supplierId: 7,
    costCenterId: "CC007",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-01-21"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 7,
  },
  {
    id: 8,
    jobId: 1,
    name: "Temp Fencing",
    supplierId: 8,
    costCenterId: "CC008",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-01-22"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 8,
  },
  {
    id: 9,
    jobId: 1,
    name: "Water Tapping",
    supplierId: 9,
    costCenterId: "CC009",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "if required",
    startDate: new Date("2024-01-23"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 9,
  },
  {
    id: 10,
    jobId: 1,
    name: "Site Sign Install",
    supplierId: 10,
    costCenterId: "CC010",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-01-24"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 10,
  },
  {
    id: 11,
    jobId: 1,
    name: "Site Toilet",
    supplierId: 11,
    costCenterId: "CC011",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-01-25"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 11,
  },
  {
    id: 12,
    jobId: 1,
    name: "Site Cut",
    supplierId: 12,
    costCenterId: "CC012",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "2d",
    startDate: new Date("2024-01-26"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 12,
  },
  {
    id: 13,
    jobId: 1,
    name: "Set Out",
    supplierId: 13,
    costCenterId: "CC013",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-01-27"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 13,
  },
  {
    id: 14,
    jobId: 1,
    name: "Bored Piers",
    supplierId: 14,
    costCenterId: "CC014",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "if required",
    startDate: new Date("2024-01-28"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 14,
  },
  {
    id: 15,
    jobId: 1,
    name: "Underground Power",
    supplierId: 15,
    costCenterId: "CC015",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d, next stage",
    startDate: new Date("2024-01-29"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 15,
  },
  {
    id: 16,
    jobId: 1,
    name: "Sewer/ Stormwater Drains / Camera Check",
    supplierId: 16,
    costCenterId: "CC016",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "2d",
    startDate: new Date("2024-01-30"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 16,
  },
  {
    id: 17,
    jobId: 1,
    name: "Spoil Removal from Drains",
    supplierId: 17,
    costCenterId: "CC017",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-01-31"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 17,
  },
  {
    id: 18,
    jobId: 1,
    name: "Termite Part A",
    supplierId: 18,
    costCenterId: "CC018",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-02-01"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 18,
  },
  {
    id: 19,
    jobId: 1,
    name: "Spoil Removal from Piers",
    supplierId: 17,
    costCenterId: "CC019",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-02-02"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 19,
  },
  {
    id: 20,
    jobId: 1,
    name: "Retaining Walls",
    supplierId: 19,
    costCenterId: "CC020",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "if required",
    startDate: new Date("2024-02-03"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 20,
  },
  {
    id: 21,
    jobId: 1,
    name: "Steel Inspection",
    supplierId: 20,
    costCenterId: "CC021",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-02-04"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 21,
  },
  {
    id: 22,
    jobId: 1,
    name: "Slab Boxing/Base/Pour",
    supplierId: 21,
    costCenterId: "CC022",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-02-05"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 22,
  },
  {
    id: 23,
    jobId: 1,
    name: "Slab Backfill / Clean",
    supplierId: 22,
    costCenterId: "CC023",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "1d",
    startDate: new Date("2024-02-06"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 23,
  },
  {
    id: 24,
    jobId: 1,
    name: "Basin Install",
    supplierId: 23,
    costCenterId: "CC024",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 1,
    notes: "",
    startDate: new Date("2024-02-07"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 24,
  },
];

const frameStageTasks: ITask[] = [
  {
    id: 25,
    jobId: 1,
    name: "Slab Claim - Slab QA",
    supplierId: 21,
    costCenterId: "CC025",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 2,
    notes: "1d",
    startDate: new Date("2024-02-08"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 1,
  },
  {
    id: 26,
    jobId: 1,
    name: "Termite Part B",
    supplierId: 18,
    costCenterId: "CC026",
    progress: ETaskProgress.Completed,
    status: ETaskStatus.Scheduled,
    stageId: 2,
    notes: "if required",
    startDate: new Date("2024-02-09"),
    purchaseOrderLinks: [],
    planLinks: [],
    order: 2,
  },
];

export const jobs: IJob[] = [
  {
    id: 1,
    name: "DEA2032 - Construction Stage",
    tasks: [...baseStageTasks, ...frameStageTasks],
  },
  {
    id: 2,
    name: "DEA2033 - Planning Stage",
    tasks: baseStageTasks.slice(0, 10).map((task) => ({
      ...task,
      id: task.id + 100,
      progress: ETaskProgress.Called,
    })),
  },
  {
    id: 3,
    name: "MAM2137 - Initial Phase",
    tasks: [
      ...baseStageTasks.slice(0, 15).map((task) => ({
        ...task,
        id: task.id + 200
      })),
      ...frameStageTasks.slice(0, 2).map((task) => ({
        ...task,
        id: task.id + 1100
      })),
    ],
  },
  {
    id: 4,
    name: "WIN1983 - Site Preparation",
    tasks: baseStageTasks.slice(5, 20).map((task) => ({
      ...task,
      id: task.id + 300,
      progress: ETaskProgress.Started,
    })),
  },
  {
    id: 5,
    name: "MAM2130 - Foundation",
    tasks: baseStageTasks.slice(10, 25).map((task) => ({
      ...task,
      id: task.id + 400,
      progress: ETaskProgress.ToCall,
    })),
  },
  {
    id: 6,
    name: "MAM2003 - Structural",
    tasks: frameStageTasks.map((task) => ({
      ...task,
      id: task.id + 500,
      progress: ETaskProgress.Called,
    })),
  },
  {
    id: 7,
    name: "MAM2114 - Finishing",
    tasks: baseStageTasks.slice(0, 8).map((task) => ({
      ...task,
      id: task.id + 600,
      progress: ETaskProgress.Completed,
    })),
  },
  {
    id: 8,
    name: "MAM2238 - Electrical",
    tasks: baseStageTasks.slice(14, 18).map((task) => ({
      ...task,
      id: task.id + 700,
      progress: ETaskProgress.Started,
    })),
  },
  {
    id: 9,
    name: "MAM2115 - Plumbing",
    tasks: baseStageTasks.slice(8, 12).map((task) => ({
      ...task,
      id: task.id + 800,
      progress: ETaskProgress.Confirmed,
    })),
  },
  {
    id: 10,
    name: "MAM2142 - HVAC",
    tasks: baseStageTasks.slice(3, 7).map((task) => ({
      ...task,
      id: task.id + 900,
      progress: ETaskProgress.Called,
    })),
  },
  {
    id: 11,
    name: "ODE209 - Landscaping",
    tasks: baseStageTasks.slice(19, 24).map((task) => ({
      ...task,
      id: task.id + 1000,
      progress: ETaskProgress.ToCall,
    })),
  },
  {
    id: 12,
    name: "MAM2033 - Final Inspection",
    tasks: [
      ...baseStageTasks.slice(20, 24).map((task) => ({
        ...task,
        id: task.id + 1100,
        progress: ETaskProgress.NotRequired,
      })),
    ],
  },
  {
    id: 13,
    name: "COB329 - Site Cleanup",
    tasks: baseStageTasks.slice(22, 24).map((task) => ({
      ...task,
      id: task.id + 1200,
      progress: ETaskProgress.Completed,
    })),
  },
  {
    id: 14,
    name: "HRT134 - Documentation",
    tasks: baseStageTasks.slice(0, 3).map((task) => ({
      ...task,
      id: task.id + 1300,
      progress: ETaskProgress.Started,
    })),
  },
];

export const folders: IFolder[] = [
  {
    id: 8,
    name: "Juzzle",
    color: "#06b6d4",
    jobs: [
      { folderId: 8, name: "MAM2137", jobId: 3 },
      { folderId: 8, name: "WIN1983", jobId: 4 },
      { folderId: 8, name: "MAM2130", jobId: 5 },
      { folderId: 8, name: "MAM2003", jobId: 6 },
      { folderId: 8, name: "MAM2114", jobId: 7 },
      { folderId: 8, name: "MAM2238", jobId: 8 },
      { folderId: 8, name: "MAM2115", jobId: 9 },
      { folderId: 8, name: "MAM2142", jobId: 10 },
      { folderId: 8, name: "ODE209", jobId: 11 },
      { folderId: 8, name: "MAM2033", jobId: 12 },
      { folderId: 8, name: "COB329", jobId: 13 },
      { folderId: 8, name: "HRT134", jobId: 14 },
    ],
  },
];
